#!/bin/bash

cd /home/frankt/linuxcnc/9x20lathe
export EMCPATH=/home/frankt/linuxcnc-dev
#export GTK2_RC_FILES=/home/frankt/linuxcnc/9x20lathe/touchy/theme/HighContrastFT/gtk-2.0/gtkrc

. $EMCPATH/scripts/rip-environment
#rm /home/frankt/emc2/9x20lathe/9x20lathe.var
$EMCPATH/scripts/linuxcnc /home/frankt/linuxcnc/9x20lathe/9x20lathe-touchy.ini
