#!/bin/bash

cd /home/frankt/linuxcnc/9x20lathe
export LINUXCNCPATH=/home/frankt/linuxcnc_src

. $LINUXCNCPATH/scripts/rip-environment
#rm /home/frankt/emc2/9x20lathe/9x20lathe.var
$LINUXCNCPATH/scripts/linuxcnc /home/frankt/linuxcnc/9x20lathe/9x20lathe.ini
#emc /home/frankt/emc2/9x20lathe/9x20lathe.ini
